ARROW-16 BSON array support
mongodb-labs/mongo-arrow pull request #119
Opened 2022-12-20 20:24 UTC by juliusgeo

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/docs/source/quickstart.rst
> +  schema = Schema({'_id': int, 'amount': float, 'account': list_(list_(int32()))})
I think we should keep it simple and use `list_(int32())` for these examples.

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/pymongoarrow/context.py
> +        self.default_builder = None
Unused

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/pymongoarrow/lib.pyx
> +from collections import defaultdict
Unused

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/pymongoarrow/lib.pyx
> +def process_bson_stream(bson_stream, context, value_builder=None):
maybe call this `array_value_builder`?

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/pymongoarrow/lib.pyx
> +        # Append an element to the Struct. "All child-builders' Append method
This comment is from the struct class

2022-12-20 21:34 UTC, blink1073 commented on bindings/python/test/test_arrow.py
> +        schema["list"] = list_(list_(int32()))
Why nest this list?

2022-12-21 01:16 UTC, blink1073 commented on bindings/python/pymongoarrow/lib.pyx
> +cdef extract_field_dtype(bson_iter_t * doc_iter, bson_iter_t * child_iter, bson_type_t value_t, context):
Needs a docstring

2022-12-21 01:16 UTC, blink1073 commented on bindings/python/test/test_arrow.py
> +        schema["list"] = list_(list_(int32()))
Yeah, I think we should add a list that contains documents, and a list that contains other lists as new tests.

2023-01-04 18:33 UTC, blink1073 requested changes

2023-01-04 18:33 UTC, blink1073 commented on bindings/python/docs/source/quickstart.rst
> +Arrays (and embedded arrays) are also supported::
I think this should be "nested arrays" as well.  I used "embedded document" because that is what it is called in the spec.

2023-01-04 18:33 UTC, blink1073 commented on bindings/python/test/test_arrow.py
> +        print(schema)
Print can be removed

2023-01-04 18:33 UTC, blink1073 commented on bindings/python/test/test_arrow.py
> +        print(schema)
Same here

2023-01-05 21:46 UTC, blink1073 requested changes

2023-01-05 21:46 UTC, blink1073 commented on bindings/python/docs/source/quickstart.rst
> +You would need to insert
Stray comment?

2023-01-09 13:55 UTC, blink1073 approved these changes
Thanks!

2023-01-09 14:33 UTC, merged

2023-01-10 22:05 UTC, ShaneHarvey commented on bindings/python/docs/source/quickstart.rst
> +  schema = Schema({'_id': int, 'amount': float, 'account': list_(int32())})
There is no account field in the example documents above. Could you open a ticket to update these examples?