ARROW-137 Remove workarounds for extension types in test suite
mongodb-labs/mongo-arrow pull request #121
Opened 2023-01-05 23:50 UTC by juliusgeo

2023-01-06 02:18 UTC, blink1073 requested changes
There is also a `.DS_Store` file committed.

2023-01-06 02:18 UTC, blink1073 commented on bindings/python/test/test_arrow.py
> +    def _create_data(self, block=False, nested=True):
What does "block" mean?  It looks like this is only ever called with `block=True`.  When would we not want to include the extension types?

2023-01-09 15:50 UTC, blink1073 commented on bindings/python/test/utils.py
> +                ObjectIdType(),
Perhaps we can check for an extension type here so we don't have to manually update?

2023-01-17 23:15 UTC, ShaneHarvey commented
Should we close this PR now based on the extra work required?

2023-01-19 08:24 UTC, closed without merging