Code fence syntax highlight in readme
mongodb-labs/mongo-arrow pull request #205
Opened 2024-04-08 14:41 UTC by janosh

quick clarifying question if i may: is this library solely concerning with reading? it does not handle numpy type conversion to BSON on DB write?

context: it appears `numpy.bool_` fails to BSON-serialize with numpy v2 https://github.com/materialsproject/fireworks/issues/522

2024-04-08 18:49 UTC, ShaneHarvey requested changes
Could you fix the pre-commit failures?

> is this library solely concerned with reading? it does not handle numpy type conversion to BSON on DB write?

We support writing as well via the write() function:
https://mongo-arrow.readthedocs.io/en/stable/quickstart.html#writing-to-mongodb

2024-04-09 05:41 UTC, janosh commented
pre-commit should be green now.

thanks for the quick reply, good to know about `write`! is there some function that recursively converts a dict containing `numpy`/`pandas` types to std lib Python types?

2024-04-09 19:56 UTC, ShaneHarvey commented
Yes, you can see it here: https://github.com/mongodb-labs/mongo-arrow/blob/1.3.0/bindings/python/pymongoarrow/api.py#L417

2024-04-09 19:56 UTC, ShaneHarvey approved these changes

2024-04-09 19:57 UTC, merged